"""followers

Revision ID: 678982125528
Revises: dbf757722a1c
Create Date: 2022-07-10 11:14:53.067123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678982125528'
down_revision = 'dbf757722a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
